[[redirects]]
  from = "/staff"
  to = "https://docs.google.com/forms/d/e/1FAIpQLSc5_otaW8RziIm3LSLTfjURUt3C_zoBIztf5rNnQUQmZO3z_g/viewform"
  status = 301
  force = true

  [[redirects]]
  from = "/captain"
  to = "https://forms.gle/awdVDBVsfzwBhug86"
  status = 301
  force = true

  [[redirects]]
  from = "/freeagent"
  to = "https://docs.google.com/forms/d/e/1FAIpQLSd_JuBchBvH2EQ9lWFsEyTsdThWO9jEDB-onCo4EsgqIX8TDg/viewform?usp=sf_link"
  status = 301
  force = true

  [[redirects]]
  from = "/irp"
  to = "https://f001.backblazeb2.com/file/ssmusspn/irp.pdf"
  status = 301
  force = true